name: Run Test Suite

on:
  pull_request:
    branches:
    - master


jobs:
  run_test_suite:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        # https://help.github.com/articles/virtual-environments-for-github-actions
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version: [3.6, 3.7]
        testcover: [yes, no]
        testml: [yes, no]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools pip wheel
        # Use the latest published version for myself :)
        python -m pip install tox-gh-actions
    - name: Test with tox
      run: tox -- -p no:sugar
      env:
        PYTEST_XDIST_PROC_NR: 2
        TESTCOVER: ${{ matrix.testcover }}
        TESTML: ${{ matrix.testml }}
    - name: Upload coverage to Codecov
      if: ${{ matrix.testcover }} == yes
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true


